// =============================================================================
// Enrol a School of Music applicant as an active student.
//
// One student doc in `users` is what every module reads, so writing it with
// the right fields is what "syncs" the student everywhere:
//   Registry (/dashboard/registry)        admissionNumber, dateOfAdmission, batchId/batch, status
//   Enrollments roster (centre students)  centerId, batchId, status "active"
//   Attendance rosters                    centerId + batchId (null = centre's General Batch)
//   Finance ledger                        billingMode "prepay", feeCycle "monthly", monthlyFee, currentBalance
// The centre's `studentUids` mirror and the screening / application links are
// updated alongside. The application is kept and marked enrolled (not deleted).
//
// Re-enrolling someone already in the Registry (same wing) never blocks: the
// new details are merged into their existing student doc instead — see
// findEnrolmentMatch + mergeIntoStudent. One student id across every module.
// =============================================================================

import {
  addDoc, arrayRemove, arrayUnion, collection, doc, getDoc, serverTimestamp, updateDoc,
} from "firebase/firestore";
import { db } from "@/services/firebase/firebase";
import { WINGS } from "@/config/constants";
import { admissionNoBlockedMessage, checkAdmissionNo } from "@/lib/admissionNumber";
import { linkAdmissionFeeToStudent } from "@/services/finance/finance.service";
import { findEnrolmentMatch, mergeStudents, type EnrolmentMatch } from "@/services/dedup/dedup.service";
import type { CenterBatch, Wing } from "@/types";
import type { SyllabusInstrument, SyllabusLevel } from "@/types/lesson";

export interface EnrollInput {
  application:   Record<string, unknown>;
  admissionId:   string;
  /** The saved Fast Track screening (needs its `id`). */
  screening:     Record<string, unknown> & { id: string };
  centreId:      string;
  /** A real batch of the centre, or null for the centre's General Batch. */
  batch:         CenterBatch | null;
  admissionNo:   string;
  instrument:    SyllabusInstrument;
  syllabusLevel: SyllabusLevel;
  monthlyFee:    number;
  /** YYYY-MM-DD — first class / start date; becomes the admission date. */
  startDate:     string;
  enrolledBy:    string;
  /** Wing the applicant was admitted to — the student is created there (default School of Music). */
  wing?:         string;
}

const str = (v: unknown) => (typeof v === "string" ? v : "");
const strArr = (v: unknown) => (Array.isArray(v) ? v.map(String) : []);

/**
 * Fields a re-enrolment never overwrites on the existing student: identity,
 * the original admission number/date, the fee set-up (Wing 1 billing is
 * protected) and ledger balance, and the first screening snapshot.
 */
const PRESERVED_ON_MERGE = new Set([
  "name", "displayName", "firstName", "middleName", "lastName", "role", "wing",
  "admissionNumber", "admissionNoAutoGenerated", "studentID", "dateOfAdmission",
  "classType", "billingMode", "feeCycle", "feePerClass", "currentBalance",
  "assignedTeacherUid", "classDays", "classTime",
  "screening", "createdVia", "admissionId", "createdAt",
]);
/** Preserved fields that are never filled in either, even when blank. */
const NEVER_FILL = new Set(["role", "wing", "currentBalance", "billingMode", "classType", "feeCycle", "feePerClass"]);
/** Always written on a re-enrolment, even when empty/null (null batch = General Batch). */
const ALWAYS_ON_MERGE = new Set(["centre", "centerId", "batchId", "batch", "status", "studentStatus", "updatedAt"]);

const isBlank = (v: unknown) => v === undefined || v === null || v === "" || (Array.isArray(v) && v.length === 0);

/**
 * Overlay a would-be new student doc onto an existing student: non-empty new
 * values win, preserved history stays (filled only where blank), and the old
 * centre's roster mirror is cleared on a centre change.
 */
export async function mergeIntoStudent(
  match: EnrolmentMatch, incoming: Record<string, unknown>, meta: { admissionId: string; enrolledBy: string },
): Promise<void> {
  const update: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(incoming)) {
    if (PRESERVED_ON_MERGE.has(k)) {
      if (!NEVER_FILL.has(k) && isBlank(match.data[k]) && !isBlank(v)) update[k] = v;
    } else if (ALWAYS_ON_MERGE.has(k) || !isBlank(v)) {
      update[k] = v;
    }
  }
  update.reEnrolledAt = new Date().toISOString();
  update.reEnrolledBy = meta.enrolledBy;
  if (meta.admissionId) update.reEnrolmentAdmissionIds = arrayUnion(meta.admissionId);
  update.updatedAt = serverTimestamp();
  await updateDoc(doc(db, "users", match.id), update);

  const prevCentre = str(match.data.centerId);
  const nextCentre = str(incoming.centerId);
  if (nextCentre && prevCentre && prevCentre !== nextCentre) {
    await updateDoc(doc(db, "centers", prevCentre), { studentUids: arrayRemove(match.id), updatedAt: serverTimestamp() })
      .catch(err => console.warn("[enroll] old centre roster mirror:", err));
  }
}

export interface EnrollResult {
  uid: string;
  /** True when an existing Registry student was updated instead of a new one created. */
  merged: boolean;
  /** Admission number the student ends up with (their original one on a merge). */
  admissionNo: string;
}

/**
 * Creates the student — or, if they're already in the Registry, merges into
 * their existing record — and links everything.
 */
export async function enrollApplicant(i: EnrollInput): Promise<EnrollResult> {
  const admNo = i.admissionNo.trim();
  if (admNo.length < 4) throw new Error("Enter the admission number (at least 4 characters).");
  if (!i.centreId) throw new Error("Select a centre.");
  if (!(i.monthlyFee > 0)) throw new Error("Enter the monthly fee.");
  // Admission fee is a mandatory prerequisite.
  const feeAmount = i.application.admissionFeeAmount;
  if (i.application.admissionFeePaid !== true || typeof feeAmount !== "number" || !(feeAmount > 0)) {
    throw new Error("Record the admission fee payment before enrolling.");
  }
  const a = i.application;
  const wing = (i.wing || WINGS.SCHOOL_OF_MUSIC) as Wing;

  // Already in the Registry (this wing)? Merge instead of creating a duplicate.
  const match = await findEnrolmentMatch(
    { name: str(a.fullName), phone: str(a.phone), dob: str(a.dob), admissionNo: admNo }, wing,
  );
  const originalAdmNo = match ? str(match.data.admissionNumber).trim() : "";
  const finalAdmNo = originalAdmNo || admNo;
  // A typed number is only assigned when the student has none yet — then it must be free.
  if (!originalAdmNo) {
    const check = await checkAdmissionNo(admNo, str(a.fullName), i.admissionId);
    // Same person, but filed under the other wing — don't merge across wings here.
    if (check.kind === "match") throw new Error(`Admission number ${admNo} is already registered to ${check.studentName} in the other wing. Please verify the number.`);
    if (check.kind !== "free") throw new Error(admissionNoBlockedMessage(admNo, check));
  }
  const admittedOn = i.startDate ? new Date(`${i.startDate}T00:00:00`).toISOString() : new Date().toISOString();
  const { id: screeningId, ...screeningData } = i.screening;

  // 1. The student record (new, or merged into the existing one).
  const studentDoc: Record<string, unknown> = {
    name:            str(a.fullName),
    displayName:     str(a.fullName),
    firstName:       str(a.firstName),
    middleName:      str(a.middleName),
    lastName:        str(a.lastName),
    role:            "student",
    wing,
    phone:           str(a.phone),
    email:           str(a.email),
    age:             str(a.age),
    dob:             str(a.dob),
    parentName:      str(a.parentName),
    workingStatus:   str(a.workingStatus),
    schoolCompany:   str(a.schoolCompany),
    address1:        str(a.address1),
    address2:        str(a.address2),
    centre:          i.centreId,
    centerId:        i.centreId,
    batchId:         i.batch?.id ?? null,
    batch:           i.batch?.name ?? null,
    admissionNumber: finalAdmNo,
    admissionNoAutoGenerated: false,
    studentID:       finalAdmNo,
    dateOfAdmission: admittedOn,
    firstClassDate:  i.startDate || null,
    instruments:     strArr(a.instrumentsToLearn),
    ...(str(a.course) ? { course: str(a.course), courseLevel: str(a.courseLevel) } : {}),
    musicalSkill:    str(a.musicalSkill),
    photo:           str(a.photo) || null,
    screening:       { ...screeningData, id: screeningId, studentId: "" },
    syllabusLevel:      i.syllabusLevel,
    syllabusInstrument: i.instrument,
    // Wing 2 fee model: group batch, prepaid, billed monthly.
    classType:          "group",
    billingMode:        "prepay",
    feeCycle:           "monthly",
    monthlyFee:         i.monthlyFee,
    feePerClass:        0,
    assignedTeacherUid: null,
    classDays:          [],
    classTime:          null,
    currentBalance:     0,
    status:             "active",
    studentStatus:      "active",
    createdVia:         "admissions",
    admissionId:        i.admissionId,
    createdAt:          serverTimestamp(),
    updatedAt:          serverTimestamp(),
  };
  let uid: string;
  if (match) {
    await mergeIntoStudent(match, studentDoc, { admissionId: i.admissionId, enrolledBy: i.enrolledBy });
    uid = match.id;
  } else {
    uid = (await addDoc(collection(db, "users"), studentDoc)).id;
  }

  // The admission-fee receipt was saved before the student existed — attach
  // it to them (and the final centre) so it shows on their Finance history.
  const feeTxId = str(a.admissionFeeTxId);
  if (feeTxId) {
    await linkAdmissionFeeToStudent(feeTxId, uid, i.centreId, finalAdmNo).catch(err =>
      console.warn("[enroll] link admission fee:", err));
  }

  // 2. Links: student ↔ screening, centre roster mirror, application → enrolled.
  // A merged student keeps their original screening snapshot (unless they had
  // none); the new screening doc is still linked to them below.
  if (!match || isBlank(match.data.screening)) {
    await updateDoc(doc(db, "users", uid), { "screening.studentId": uid, updatedAt: serverTimestamp() });
  }
  await Promise.all([
    updateDoc(doc(db, "screenings", screeningId), { studentId: uid }).catch(err =>
      console.warn("[enroll] link screening:", err)),
    updateDoc(doc(db, "centers", i.centreId), { studentUids: arrayUnion(uid), updatedAt: serverTimestamp() }).catch(err =>
      console.warn("[enroll] centre roster mirror:", err)),
    updateDoc(doc(db, "admissions", i.admissionId), {
      admissionNumber:   finalAdmNo,
      ...(match && finalAdmNo !== admNo ? { requestedAdmissionNumber: admNo } : {}),
      ...(match ? { mergedIntoExisting: true, mergeReasons: match.reasons } : {}),
      enrolledStudentId: uid,
      enrolledAt:        new Date().toISOString(),
      enrolledBy:        i.enrolledBy,
      enrolledCentreId:  i.centreId,
      enrolledBatchId:   i.batch?.id ?? null,
      status:            "enrolled",
      updatedAt:         new Date().toISOString(),
    }),
  ]);
  return { uid, merged: !!match, admissionNo: finalAdmNo };
}

/**
 * Edit Application → "Confirm & Merge Record": the application's number and
 * name match an existing student. Overlay the application's details onto that
 * student (same rules as a re-enrolment — identity, original admission number,
 * fee set-up and balance are preserved), move the admission-fee receipt and the
 * screening to them, and link the application as enrolled into them. If the
 * application was already enrolled as a different student record, that record
 * is merged into the existing one (attendance, fees, screenings… re-pointed).
 */
export async function mergeApplicationIntoStudent(i: {
  application: Record<string, unknown>;
  admissionId: string;
  studentUid:  string;
  /** Centre doc id resolved from the application's centre, if any. */
  centreId?:   string | null;
  by:          string;
}): Promise<void> {
  const snap = await getDoc(doc(db, "users", i.studentUid));
  if (!snap.exists()) throw new Error("That student record no longer exists.");
  const student = snap.data() as Record<string, unknown>;
  const a = i.application;
  const incoming: Record<string, unknown> = {
    phone:         str(a.phone),
    email:         str(a.email),
    age:           str(a.age),
    dob:           str(a.dob),
    parentName:    str(a.parentName),
    workingStatus: str(a.workingStatus),
    schoolCompany: str(a.schoolCompany),
    address1:      str(a.address1),
    address2:      str(a.address2),
    instruments:   strArr(a.instrumentsToLearn),
    ...(str(a.course) ? { course: str(a.course), courseLevel: str(a.courseLevel) } : {}),
    musicalSkill:  str(a.musicalSkill),
    photo:         str(a.photo) || null,
    ...(i.centreId ? { centre: i.centreId, centerId: i.centreId } : {}),
  };
  await mergeIntoStudent({ id: i.studentUid, data: student, reasons: ["same name", "same admission number"] }, incoming,
    { admissionId: i.admissionId, enrolledBy: i.by });
  if (i.centreId && str(student.centerId) !== i.centreId) {
    await updateDoc(doc(db, "centers", i.centreId), { studentUids: arrayUnion(i.studentUid), updatedAt: serverTimestamp() })
      .catch(err => console.warn("[merge] centre roster mirror:", err));
  }

  // Consolidate: fee receipt + screening under the kept student id.
  const admNo = str(student.admissionNumber) || str(student.admissionNo) || str(a.admissionNumber);
  const feeTxId = str(a.admissionFeeTxId);
  if (feeTxId) {
    await linkAdmissionFeeToStudent(feeTxId, i.studentUid, i.centreId || str(student.centerId), admNo)
      .catch(err => console.warn("[merge] link admission fee:", err));
  }
  const screeningId = str(a.screeningId);
  if (screeningId) {
    await updateDoc(doc(db, "screenings", screeningId), { studentId: i.studentUid })
      .catch(err => console.warn("[merge] link screening:", err));
  }
  // Already enrolled as a different record → fold that record into this one.
  const prevUid = str(a.enrolledStudentId);
  if (prevUid && prevUid !== i.studentUid) await mergeStudents(i.studentUid, prevUid, i.by);

  await updateDoc(doc(db, "admissions", i.admissionId), {
    admissionNumber:    admNo,
    enrolledStudentId:  i.studentUid,
    mergedIntoExisting: true,
    mergeReasons:       ["same name", "same admission number"],
    status:             "enrolled",
    enrolledAt:         str(a.enrolledAt) || new Date().toISOString(),
    enrolledBy:         str(a.enrolledBy) || i.by,
    updatedAt:          new Date().toISOString(),
  });
}
