// =============================================================================
// Enrol a School of Music applicant as an active student.
//
// One student doc in `users` is what every module reads, so writing it with
// the right fields is what "syncs" the student everywhere:
//   Registry (/dashboard/registry)        admissionNumber, dateOfAdmission, batchId/batch, status
//   Enrollments roster (centre students)  centerId, batchId, status "active"
//   Attendance rosters                    centerId + batchId (null = centre's General Batch)
//   Finance ledger                        billingMode "prepay", feeCycle "monthly", monthlyFee, currentBalance
// The centre's `studentUids` mirror and the screening / application links are
// updated alongside. The application is kept and marked enrolled (not deleted).
// =============================================================================

import {
  addDoc, arrayUnion, collection, doc, serverTimestamp, updateDoc,
} from "firebase/firestore";
import { db } from "@/services/firebase/firebase";
import { WINGS } from "@/config/constants";
import { isAdmissionNoTaken } from "@/lib/admissionNumber";
import type { CenterBatch } from "@/types";
import type { SyllabusInstrument, SyllabusLevel } from "@/types/lesson";

export interface EnrollInput {
  application:   Record<string, unknown>;
  admissionId:   string;
  /** The saved Fast Track screening (needs its `id`). */
  screening:     Record<string, unknown> & { id: string };
  centreId:      string;
  /** A real batch of the centre, or null for the centre's General Batch. */
  batch:         CenterBatch | null;
  admissionNo:   string;
  instrument:    SyllabusInstrument;
  syllabusLevel: SyllabusLevel;
  monthlyFee:    number;
  /** YYYY-MM-DD — first class / start date; becomes the admission date. */
  startDate:     string;
  enrolledBy:    string;
}

const str = (v: unknown) => (typeof v === "string" ? v : "");
const strArr = (v: unknown) => (Array.isArray(v) ? v.map(String) : []);

/** Creates the student and links everything. Returns the new student's uid. */
export async function enrollApplicant(i: EnrollInput): Promise<string> {
  const admNo = i.admissionNo.trim();
  if (admNo.length < 4) throw new Error("Enter the admission number (at least 4 characters).");
  if (!i.centreId) throw new Error("Select a centre.");
  if (!(i.monthlyFee > 0)) throw new Error("Enter the monthly fee.");
  if (await isAdmissionNoTaken(admNo, i.admissionId)) {
    throw new Error(`Admission number ${admNo} is already in use. Please enter a different one.`);
  }

  const a = i.application;
  const admittedOn = i.startDate ? new Date(`${i.startDate}T00:00:00`).toISOString() : new Date().toISOString();
  const { id: screeningId, ...screeningData } = i.screening;

  // 1. The student record.
  const userRef = await addDoc(collection(db, "users"), {
    name:            str(a.fullName),
    displayName:     str(a.fullName),
    firstName:       str(a.firstName),
    middleName:      str(a.middleName),
    lastName:        str(a.lastName),
    role:            "student",
    wing:            WINGS.SCHOOL_OF_MUSIC,
    phone:           str(a.phone),
    email:           str(a.email),
    age:             str(a.age),
    dob:             str(a.dob),
    parentName:      str(a.parentName),
    workingStatus:   str(a.workingStatus),
    schoolCompany:   str(a.schoolCompany),
    address1:        str(a.address1),
    address2:        str(a.address2),
    centre:          i.centreId,
    centerId:        i.centreId,
    batchId:         i.batch?.id ?? null,
    batch:           i.batch?.name ?? null,
    admissionNumber: admNo,
    admissionNoAutoGenerated: false,
    studentID:       admNo,
    dateOfAdmission: admittedOn,
    firstClassDate:  i.startDate || null,
    instruments:     strArr(a.instrumentsToLearn),
    musicalSkill:    str(a.musicalSkill),
    photo:           str(a.photo) || null,
    screening:       { ...screeningData, id: screeningId, studentId: "" },
    syllabusLevel:      i.syllabusLevel,
    syllabusInstrument: i.instrument,
    // Wing 2 fee model: group batch, prepaid, billed monthly.
    classType:          "group",
    billingMode:        "prepay",
    feeCycle:           "monthly",
    monthlyFee:         i.monthlyFee,
    feePerClass:        0,
    assignedTeacherUid: null,
    classDays:          [],
    classTime:          null,
    currentBalance:     0,
    status:             "active",
    studentStatus:      "active",
    createdVia:         "admissions",
    admissionId:        i.admissionId,
    createdAt:          serverTimestamp(),
    updatedAt:          serverTimestamp(),
  });
  const uid = userRef.id;

  // 2. Links: student ↔ screening, centre roster mirror, application → enrolled.
  await updateDoc(userRef, { "screening.studentId": uid, updatedAt: serverTimestamp() });
  await Promise.all([
    updateDoc(doc(db, "screenings", screeningId), { studentId: uid }).catch(err =>
      console.warn("[enroll] link screening:", err)),
    updateDoc(doc(db, "centers", i.centreId), { studentUids: arrayUnion(uid), updatedAt: serverTimestamp() }).catch(err =>
      console.warn("[enroll] centre roster mirror:", err)),
    updateDoc(doc(db, "admissions", i.admissionId), {
      admissionNumber:   admNo,
      enrolledStudentId: uid,
      enrolledAt:        new Date().toISOString(),
      enrolledBy:        i.enrolledBy,
      enrolledCentreId:  i.centreId,
      enrolledBatchId:   i.batch?.id ?? null,
      status:            "enrolled",
      updatedAt:         new Date().toISOString(),
    }),
  ]);
  return uid;
}
